# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsData',
        ),
    ]
