# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.UserData')),
            ],
        ),
        migrations.AddField(
            model_name='answerdata',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discussion.QuestionData'),
        ),
        migrations.AddField(
            model_name='answerdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.UserData'),
        ),
    ]
