# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdata',
            name='area',
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='name',
        ),
        migrations.AddField(
            model_name='addressdata',
            name='area_english',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='area_hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='city_english',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='city_hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='locality_english',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='locality_hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='name_english',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='name_hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='state_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='state_hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='house_number',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
