# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0002_auto_20180203_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropArrangementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_size', models.CharField(max_length=255)),
                ('bed_lines', models.CharField(max_length=255)),
                ('seeds', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CropSpacingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=20)),
                ('spacing', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='croparrangementdata',
            name='crop_spacing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.CropSpacingData'),
        ),
        migrations.AddField(
            model_name='croparrangementdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.UserData'),
        ),
    ]
