# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name_english', models.TextField()),
                ('disease_name_hindi', models.TextField()),
                ('symptoms_english', models.TextField()),
                ('symptoms_hindi', models.TextField()),
                ('prevention_english', models.TextField()),
                ('prevention_hindi', models.TextField()),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
